
services:
  app:
    runtime: registry-cn-beijing-vpc.ack.aliyuncs.com/alinux3/node
    build:
      script: sh ./build.sh
      dir: ./out
    run:
      cmd: node app.js
      env:
        a: b
        token: a
        MYSQL_PSM: $(MYSQL_PSM)
    resources:
      cpu: 2
      mem: 2
      instances:
        min: 1
        max: 100
  
vars:
  MYSQL_PSM: import('global/bus-dbs').services.mysql.actual.PSM

